# Generated by Django 5.0.4 on 2024-07-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_item_first_name_remove_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='blood_type',
            field=models.CharField(default='O+', max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='citizenship',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='civil_status',
            field=models.CharField(default='Single', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='college',
            field=models.CharField(default='Unknown College', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='item',
            name='elementary',
            field=models.CharField(default='Unknown Elementary', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='father_first_name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='father_last_name',
            field=models.CharField(default='Smith', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='father_middle_name',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_first_name',
            field=models.CharField(default='Jane', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_last_name',
            field=models.CharField(default='Smith', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_middle_name',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='occupation',
            field=models.CharField(default='Unemployed', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='place_of_birth',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='secondary',
            field=models.CharField(default='Unknown High School', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='sex',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='zip_code',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='first_name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_name',
            field=models.CharField(default='Smith', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='middle_name',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
    ]
