# Generated by Django 5.0.4 on 2024-07-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_blood_type_item_citizenship_item_civil_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='father_first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='father_last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='father_middle_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='first_name',
            field=models.CharField(default='Edcel', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_name',
            field=models.CharField(default='Capuyan', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='middle_name',
            field=models.CharField(default='Aspera', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='mother_first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='mother_last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='mother_middle_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
