# Generated by Django 5.0.6 on 2024-07-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_middlena_me_item_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='agency_employee_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='blood_type',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='citizenship',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='civil_status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_of_birth',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='email_address',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='item',
            name='fathers_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='gsis_id_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='middle_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='mobile_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='mothers_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='pagibig_id_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='permanent_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='philhealth_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='place_of_birth',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='residential_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='sss_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='telephone_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='tin_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='zip_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
